### ISSUE TITLE
Language regarding resignation and termination of lesson programs

### ISSUE THREAD

**Issue by amyehodge** [carpentries/2018_Bylaws#10]
v2 currently states:

"Resignation and Termination of Lesson Programs
In the event that Lesson Programs fail to meet the responsibilities described above, the Executive Council may decide to retire the Lesson Program through a majority vote. If the Lesson Program Committee chooses to discontinue the Lesson Program’s association with The Carpentries, they must inform the Executive Council to arrange for separation of responsibilities and resources."

I'm somewhat uncomfortable with this presenting the possibility that Lesson Program may not fulfill their responsibilities and does not mention that The Carpentries might not fulfill their responsibilities. I hope we do, but it fills a bit one-sided. There is some language in the [Lesson Program](https://docs.google.com/document/d/1gHti3NeXLMNarGpATredWxgJdYvU6Wy2h322V2xMQJA/edit) document (at the very end) that might be massageable for this here.

Suggestion: "In the event that either the Lesson Program or The Carpentries is not fulfilling its obligations under the Lesson Program Policy, or the mission and vision of The Carpentries and the Lesson Program no longer align, the relationship between the Lesson Program and the Carpentries can be severed. The Executive Council may decide to retire the Lesson Program through a majority vote, or the Lesson Program Committee can choose to discontinue the Lesson Program's association with the Carpentries. In either case, notice must be given to the other organization to arrange for separation of responsibilities and resources."

**Comment by k8hertweck** [comment]
Thanks, your suggestion has been accepted in #14
