### ISSUE TITLE
Target question 2: How should the Executive Council seek nominations for appointed candidates?

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/2018_Bylaws#2]
The bylaws describe a composition of the Executive Council which includes both elected and appointed members. While the former are selected by the community at large, the latter are selected by the Executive Council. Section 6 of the bylaws specify that the Executive Council will accept recommendations from the community for appointed members. Do we need to specify more clearly the mechanism through which we accept nominees?

**Comment by weaverbel** [comment]
Yes, we would need to have a specific time frame for nominations and a mechanism for nominating. This also means enough lead time to get the word out that this is coming @k8hertweck

**Comment by npch** [comment]
+1 to @weaverbel comments, but I also don't think that the wording in the bylaws should be too detailed (e.g. should this be through email versus an anonymous service versus Github issues), instead it should only focus on the timeframe and who is responsible.

I would also suggest that the Executive Council keep an up to date skills register of EC members and map this against the current skills requirements for the organisation, and use this to help guide nominations, but this shouldn't be in the Bylaws, just in other guidance around governance and elections.

**Comment by k8hertweck** [comment]
The updates to the election process are included in #13
