### ISSUE TITLE
Clean up / archive this repo?

### ISSUE THREAD

**Issue by kcranston** [carpentries/2018_Bylaws#26]
Current version of bylaws now [in handbook](https://docs.carpentries.org/topic_folders/governance/bylaws.html). (yay!) Do we still need this repo? If not, we should archive it. Otherwise, should cleanup up readme, remove draft versions of bylaws, etc.

**Comment by lexnederbragt** [comment]
I would be in favour of archiving this repo, avoiding having two copies of the same bylaws

**Comment by kcranston** [comment]
General agreement in the EC meeting about archiving this repo. I do not have permission to do so. @ErinBecker @fmichonneau ?

**Comment by fmichonneau** [comment]
Archiving project.
