### ISSUE TITLE
What is  Lesson Program Membership

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/2018_Bylaws#3]
I am not clear what a lesson program is after reading the bylaws. Is Data Carpentry a lesson program, are the Genomics Lessons a lesson program? I'm sure this made sense to people on the inside but was not clear to me.

**Comment by wrightaprilm** [comment]
I agree with this. And does this mean that the "lesson organization" (i.e. Data v. Software v. Library) terminology is being retired? Or is that going to be used, but each organization is adopting this unified set of policies?

**Comment by k8hertweck** [comment]
We've decided not to include specific examples in the bylaws, but in short, Data Carpentry and Software Carpentry are each Lesson Programs, and this language is now the "official" label.
