### ISSUE TITLE
Regular Meetings and Quorum too many and too small?

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [carpentries/2018_Bylaws#6]
I think quorum should be 6, since a quorum of 5 could create a situation where importance business could be conducted with only the nominated (and not elected) members present. Also, 10 meetings is a high bar for some of the really experienced (and likely very busy) members that should be a part of this group. Maybe 4-6 is the minimum, although of course monthly is great if people can do it.

**Comment by npch** [comment]
For clarification is:

"The Executive Council must meet at least ten (10) times per year"

a requirement on the EC as a whole ('The Carpentries Executive Council must hold at least 10 meetings a year"), or the individual members ("Each Carpentries Executive Council Member must attend at least 10 meetings a year")?

**Comment by k8hertweck** [comment]
We've updated the quorum to require at least one Community-elected and one Council-elected member (in #11 ). The 10 meetings a year is per EC as a whole.
