### ISSUE TITLE
Termination of individual membership

### ISSUE THREAD

**Issue by karinlag** [carpentries/2018_Bylaws#8]
There is a "Resignation and Termination" section, but it only mentions people resigning. We do have situations where we have to terminate people's memberships. As far as I can see, there are no provisions for doing that according to the bylaws.

**Comment by k8hertweck** [comment]
This point is well taken. My initial reaction is that the Code of Conduct and enforcement thereof are the only mechanism through which we would terminate individual membership, but then I realized that the Code of Conduct isn't mentioned anywhere in the bylaws yet!

Tagging @carpentries/executive-council-2018 for additional opinions.

**Comment by rgaiacs** [comment]
I think that we had some language about the Executive Council be able to terminate individual membership but we remove in favour of one language saying the "Code of Conduct" Enforcement Subcommittee and we got into troubles because the subcommittee wasn't well defined in the bylaws.

**Comment by mkuzak** [comment]
I think the name is Code of Conduct Committee now.

**Comment by lexnederbragt** [comment]
One of the resolutions of the enforcement manual in the [CoC](
https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html) is

>A permanent or temporary ban from some or all Carpentry spaces (listservs, GitHub, in-person events including workshops, etc).

I can imagine the Bylaws mentioning that in cases where the CoC imposes a permanent ban, the Executive Council automatically votes on ending the offender’s membership?

**Comment by karinlag** [comment]
I also recommend that you bear in mind that there might be situations outside of the CoC's purview. What if somebody actively misrepresents the Carpentries somewhere? What if somebody has embezzled money from a workshop? Those two mentioned cases would not really be covered by the CoC and thus not fall under what the CoC could terminate people's memberships over. I can easily imagine that there could be other situations too that would cause us to want to sever people's association with the Carpentries.

**Comment by tracykteal** [comment]
Suggested the text "Voting Membership may be terminated by a majority vote of the Executive Council for individuals who are recommended for termination by the Code of Conduct committee or Executive Director for non-compliance with Carpentries policies."

That would allow termination to cover all policies, including things like embezzlement that @karinlag mentioned. Then the CoC committee or ED could bring that recommendation, and why they have that recommendation based on their processes and policies, to the EC for them to vote.

**Comment by k8hertweck** [comment]
Language added as per #24
