### ISSUE TITLE
Unclear description of elections

### ISSUE THREAD

**Issue by karinlag** [carpentries/2018_Bylaws#9]
I know you state that there will be a more detailed Elections document. However I still think that the information that is in the bylaws already could do with a bit of tidying up. For instance, a deadline for when the vote on appointed members is mentioned (15 Dec) with a reference of the election of elected members, however, at that stage in the text, no dates for the election is mentioned. Also, how come the election of Appointed members are mentioned in the section of Elected members?

"The Executive Council will seek candidates for Elected Members seats that become vacant. Two (2) of the Appointed Member seats shall be filled at each election. "

I suggest a short overarching section first, with a description of the order in which things will happen, followed by a descripton of how Appointed and Elected members will be elected.

**Comment by k8hertweck** [comment]
We've added a timeline and overview, as you suggest, and have hopefully clarified language adequately in #13
